/*==============================================================*/
/* Table: GENERO                                                */
/*==============================================================*/
/*CREATE TABLE GENERO (
   ID_GENERO            VARCHAR(3)            NOT NULL,
   TIPO                 VARCHAR(50),
   CONSTRAINT PK_GENERO PRIMARY KEY (ID_GENERO)
);*/

INSERT INTO GENERO (ID_GENERO,TIPO) VALUES ('001','COMEDIA');
INSERT INTO GENERO (ID_GENERO,TIPO) VALUES ('002','DRAMA');
INSERT INTO GENERO (ID_GENERO,TIPO) VALUES ('003','ACCION');
INSERT INTO GENERO (ID_GENERO,TIPO) VALUES ('004','CIENCIA FICCION');
INSERT INTO GENERO (ID_GENERO,TIPO) VALUES ('005','TERROR');
INSERT INTO GENERO (ID_GENERO,TIPO) VALUES ('006','COMEDIA');
INSERT INTO GENERO (ID_GENERO,TIPO) VALUES ('007','FANTASIA');
INSERT INTO GENERO (ID_GENERO,TIPO) VALUES ('008','ROMANTICA');
INSERT INTO GENERO (ID_GENERO,TIPO) VALUES ('009','SUSPENSO');