/*==============================================================*/
/* Table: CONSUMIBLES                                           */
/*==============================================================*/
/*CREATE TABLE CONSUMIBLES (
   ID_CONSUMIBLES       VARCHAR(3)            NOT NULL,
   NOMBRE               VARCHAR(30)           NOT NULL,
   PRECIO               FLOAT                 NOT NULL,
   CONSTRAINT PK_CONSUMIBLES PRIMARY KEY (ID_CONSUMIBLES)
);*/

INSERT INTO CONSUMIBLES (ID_CONSUMIBLES,NOMBRE,PRECIO) VALUES ('001','PAPAS MARGARITA',3.5);
INSERT INTO CONSUMIBLES (ID_CONSUMIBLES,NOMBRE,PRECIO) VALUES ('002','GOMITAS DE OSO',2.5);
INSERT INTO CONSUMIBLES (ID_CONSUMIBLES,NOMBRE,PRECIO) VALUES ('003','GOMAS DE MASCAR',1.0);
INSERT INTO CONSUMIBLES (ID_CONSUMIBLES,NOMBRE,PRECIO) VALUES ('003','GOMAS DE MASCAR',1.0);
INSERT INTO CONSUMIBLES (ID_CONSUMIBLES,NOMBRE,PRECIO) VALUES ('004','JUGO DE FRUTAS',3.0);
INSERT INTO CONSUMIBLES (ID_CONSUMIBLES,NOMBRE,PRECIO) VALUES ('005','GOMAS DE MASCAR',2.0);
INSERT INTO CONSUMIBLES (ID_CONSUMIBLES,NOMBRE,PRECIO) VALUES ('006','MUFFING',2.5);
INSERT INTO CONSUMIBLES (ID_CONSUMIBLES,NOMBRE,PRECIO) VALUES ('007','BEBIDA GRANDE',4,0);