/*==============================================================*/
/* Table: PROMOCION                                             */
/*==============================================================*/
/*CREATE TABLE PROMOCION (
   ID_PROMOCION         VARCHAR(5)           NOT NULL,
   NOMBRE_REFERENCIA    VARCHAR(50)          NULL,
   PORCENTAJE_DESCUENTO DECIMAL              NULL,
   CONSTRAINT PK_PROMOCION PRIMARY KEY (ID_PROMOCION)
);*/

INSERT INTO PROMOCION (I_PROMOCION,NOMBRE_REFERENCIA,PORCENTAJE_DESCUENTO) VALUES('01','FRUVERDAY',0.25);
INSERT INTO PROMOCION (I_PROMOCION,NOMBRE_REFERENCIA,PORCENTAJE_DESCUENTO) VALUES('02','CDO.PERSONAL',0.30);
INSERT INTO PROMOCION (I_PROMOCION,NOMBRE_REFERENCIA,PORCENTAJE_DESCUENTO) VALUES('03','REF.ALPINA',0.20);
INSERT INTO PROMOCION (I_PROMOCION,NOMBRE_REFERENCIA,PORCENTAJE_DESCUENTO) VALUES('04','MEATDAY',0.25);