/*==============================================================*/
/* Table: DEPARTAMENTO                                          */
/*==============================================================*/
/*CREATE TABLE DEPARTAMENTO (
   ID_DEPTO             VARCHAR(2)            NOT NULL,
   IS_PAIS              VARCHAR(2),
   NOMBRE               VARCHAR(20)           NOT NULL,
   CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID_DEPTO)
);*/

INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('91','CO','Amazonas');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('5','CO','Antioquia');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('81','CO','Arauca');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('88','CO','Archipiélago de San Andrés');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('8','CO','Atlántico');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('11','CO','Bogotá, D.C.');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('13','CO','Bolívar');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('15','CO','Boyacá');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('17','CO','Caldas');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('18','CO','Caquetá');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('85','CO','Casanare');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('19','CO','Cauca');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('20','CO','Cesar');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('27','CO','Chocó');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('23','CO','Córdoba');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('25','CO','Cundinamarca');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('94','CO','Guainía');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('95','CO','Guaviare');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('41','CO','Huila');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('44','CO','La Guajira');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('47','CO','Magdalena');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('50','CO','Meta');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('52','CO','Nariño');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('54','CO','Norte de Santander');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('86','CO','Putumayo');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('63','CO','Quindio');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('66','CO','Risaralda');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('68','CO','Santander');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('70','CO','Sucre');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('73','CO','Tolima');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('76','CO','Valle del Cauca');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('97','CO','Vaupés');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('99','CO','Vichada');
INSERT INTO DEPARTAMENTO(ID_DEPTO,IS_PAIS,NOMBRE) VALUES('','CO','Total Nacional');

